### ISSUE TITLE
Module internal naming

### ISSUE THREAD

**Issue by CodingCarlos** [Videona/platform-frontend#1]
Would be nice to define what's the best way to name views, controllers, services and directives inside the component folder. There are some options:
```
pages
    / home
        - view.html
        - controller.js
        - service.js
```
or 
```
pages
    / home
        - home.html
        - home-ctrl.js
        - home.js
```
or 
```
pages
    / home
        - home.html
        - crl-home.js
        - home.js
```
or any other option.

I have being thinking a little bit about this, and... I don't know what's the best practice.

#### My opinion

I like so much the idea of calling the internal files just as the "function" it has (view, controller...), but when you have some of them open on an editor, might be confusing have the same name for every view.

**Comment by DevStarlight** [comment]
After reading so much, working with several frameworks which includes the new angular version and swift and think about it, my conclusions are:

- Naming the file according to its behavior is good to clarify for what is used (Some people say that by watching the extension of the file is just enough, but I don't find any negative point by reinforcing the meaning).
- Start naming the file by its directory (option 2 of your question), helps clarification when you have a long tree of directories with lots of files inside, all of them displayed.
- Just a reference of what new versions of other frameworks or new versions of angular are doing... all of them are detailing like option 2:
  - swift: componentNameController.swift
  - angular: componentName.controller.ts

Hope it helps.

**Comment by CodingCarlos** [comment]
Good to read that! It seems the option `whateverController.js` will be the winning one. Also, have the same filename than the controller name.

So, my view now is on Services vs Directives naming. For both of them, AngularJS conventions recommend avoiding the "Service" or "Directive" suffix, so... How will we keep it clear? The little devil on my shoulder tells me that folder name will give us the key (`/components` for directives, or `/pages` for services), but... I don't know if all the cases will be covered by this _"rule"_... And also, what about _filters_?

I'll think a little bit more about this, before making decisions.

**Comment by DevStarlight** [comment]
Then it seems angularJS and Angular teams doesn't talk too much about the convention that each of them are following. My point of view about that is:

- Services that are directly related to the page under the path, then I'd follow the same convention as the views, the controllers or the scss..., just reinforcing the meaning of the file e.g:
   ```
  pages
     /home
        home.view.html
        home.view.scss
        home.controller.js
        home.service.js
   ```
- Talking about a more global service... I would omit that naming extension, since there's already a path reinforcing the meaning and it's completelly clear there's no other kind of file under that path... e.g:
   ```
  services
     session.js // all stuff related to the session 
     api.js // global callings to the backend
     global.js // Some global stuff that our app manages...
     ...
   ```
- Talking about directives... and thinking a lot about that... I haven't any oppinion. For me, directives are full chaos, cause everything can be a directive... I'd try to find rules like... if you are gonna use that method/structure more than once or twice, then it goes into a directive, but after 2 years thinking about that, people are divided and my mind has no preference.

- Talking about filters... it depends of the strategy that you're going to follow, but my experience is: keep the files as global as possible since you don't know what is gonna be useful in the near future. As well, it's not gonna happen to have a filter that inherit the name of the page, for that reason, I'd set all globally under filters or helpers, e.g:
  ```
  filters || helpers
     camelCase.js // filter that sets a string of words in camelCase 
     filter1.js // filter that replace the word king for plane
     ...
   ```

I wouldn't like to miss the possibility to work with components that angularJS 1.5.6 or higher versions. It's kind of the same that working with what we have right now and the structure is oriented to Angular, so in case the AngularJS team decide to stop supporting the project and/or we are paid hundreds of $ for migrate the platform until the last version of Angular. Keep an eye of a controller file:

```
(function () {

  angular.module('catsApp').component('componentCat', {
    controller: CatController,
    controllerAs: 'myCat',
    scope: true,
    templateUrl: 'components/category/category.html',
    require: {
      mainCtrl: '?^main'
    }
  });

  CatController.$inject = [
    'catFactory',
    '$stateParams',
    ...
  ];

  function CatController(
    catFactory,
    $stateParams
  ) {

    var vm = this, str;

    //intial setup
    vm.error = null;
    vm.state = $stateParams.id;
    vm.active = false;

    vm.$onInit = function () {
      vm.posterSize = vm.mainCtrl.posterSize;
    };

    vm.catImage = globalFactory.getCatPoster($stateParams.id);
  }

}());

```

**Comment by CodingCarlos** [comment]
Hummmm... I had never seen a component for a controller. According to [AngularJS docs for components](https://docs.angularjs.org/guide/component),
> a Component is a special kind of directive that uses a simpler configuration which is suitable for a component-based application structure.

Actually... I think that the example you're providing is not a controller itself, but a component who implements a controller. That's a little bit confusing when you think about pages, because you will also need a router, who have to load a page in an `ui-view`, so you'll need to have for pages

 - A page component HTML
 - An HTML template for the router to load, who only have the component (loaded as a directive).

Little tricky for pages, I think it increases development complexity.

But it seems a good choice to replace almost all directives in `/components` folder, except (according to [AngularJS docs](https://docs.angularjs.org/guide/component)):
 - for directives that need to perform actions in compile and pre-link functions, because they aren't available
 - when you need advanced directive definition options like priority, terminal, multi-element
 - when you want a directive that is triggered by an attribute or CSS class, rather than an element

**Comment by CodingCarlos** [comment]
About naming (i forgot to mention) I like the idea of adding component name and component function. I've never used dots to separe component name and function, but seems a good option when the component needs dashes to clarify the name, i.e.:
```
my-cool-name.controller.js
```
  
In case we use directives or components, the name will just be:
```
my-cool-name.directive.js
```
or
```
my-cool-name.component.js
```

**Comment by CodingCarlos** [comment]
https://github.com/Videona/platform-frontend/wiki/Naming-conventions

**Comment by CodingCarlos** [comment]
linted all in  #14
